### ISSUE TITLE
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR during training

### ISSUE THREAD

**Issue by Cyuanwen** [qcf-568/MIML#12]
Hello, thank you for your excellent work. I'm encountering an error when attempting to train a model using my custom dataset, and I would appreciate your guidance in resolving it.
The error occurs in the line "runner.run(data_loaders, cfg.workflow)" of  "mmseg/apis/train.py" during the training process. Here is the traceback:
```
Exception has occurred: RuntimeError
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 512, 128, 128], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 2, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    memory_format = Contiguous
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f3f9400c6d0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 512, 128, 128, 
    strideA = 8388608, 16384, 128, 1, 
output: TensorDescriptor 0x7f3f9400bae0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 2, 128, 128, 
    strideA = 32768, 16384, 128, 1, 
weight: FilterDescriptor 0x7f3f94043fa0
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 2, 512, 1, 1, 
Pointer addresses: 
    input: 0x7f4065c00000
    output: 0x7f47c07ab400
    weight: 0x7f47c07eb400
  File "/home/work/chenyuanwen/TTD/MIML/models for IML/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/work/chenyuanwen/TTD/MIML/models for IML/tools/train.py", line 231, in main
    train_segmentor(
  File "/home/work/chenyuanwen/TTD/MIML/models for IML/tools/train.py", line 242, in <module>
    main()
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.
```
I have run the given code, but the error doesn't show again. 

My envioriment:
```
sys.platform: linux
Python: 3.9.23 (main, Jun  5 2025, 13:40:20) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-PCIE-40GB
CUDA_HOME: None
GCC: gcc (GCC) 8.2.0
PyTorch: 1.13.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
```

**Comment by qcf-568** [comment]
@Cyuanwen Please show me your config file. What is the input shape? What is your start command? What are the values of your mask annotations (0-1 or 0-255)?

**Comment by Cyuanwen** [comment]
Thank you, I have solved it. It's ok when I run the train.py with two GPUs.
